/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BotConfig {
  'pair' : string,
  'maxTrades' : bigint,
  'apiKey' : string,
  'apiSecret' : string,
  'capital' : number,
}
export interface BotState {
  'rsi' : number,
  'lastPrice' : number,
  'consecutiveLosses' : bigint,
  'ema200' : number,
  'ema50' : number,
  'totalPnL' : number,
  'capital' : number,
  'isRunning' : boolean,
  'openTradesCount' : bigint,
}
export interface PnLSummary {
  'totalTrades' : bigint,
  'totalPnL' : number,
  'winningTrades' : bigint,
  'winRate' : number,
}
export interface Trade {
  'id' : bigint,
  'pnl' : [] | [number],
  'status' : string,
  'closeTime' : [] | [bigint],
  'pair' : string,
  'size' : number,
  'entryPrice' : number,
  'closeReason' : [] | [string],
  'exitPrice' : [] | [number],
  'openTime' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCapital' : ActorMethod<[number], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'closeTrade' : ActorMethod<[bigint, number, string], [bigint, number]>,
  'configure' : ActorMethod<[BotConfig], undefined>,
  'getAllTradeCountSorted' : ActorMethod<[], Array<Trade>>,
  'getAllTradesSortedByTradeSize' : ActorMethod<[], Array<Trade>>,
  'getBotState' : ActorMethod<[], BotState>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOpenTradesByTradeSize' : ActorMethod<[], Array<Trade>>,
  'getOpenTradesCount' : ActorMethod<[], Array<Trade>>,
  'getOpenTradesSorted' : ActorMethod<[], Array<Trade>>,
  'getPnLSummary' : ActorMethod<[], PnLSummary>,
  'getTradeCount' : ActorMethod<[], Array<Trade>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'manualTick' : ActorMethod<[], string>,
  'resetBot' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startBot' : ActorMethod<[], undefined>,
  'stopBot' : ActorMethod<[], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];