/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BotConfig = IDL.Record({
  'pair' : IDL.Text,
  'maxTrades' : IDL.Nat,
  'apiKey' : IDL.Text,
  'apiSecret' : IDL.Text,
  'capital' : IDL.Float64,
});
export const Trade = IDL.Record({
  'id' : IDL.Nat,
  'pnl' : IDL.Opt(IDL.Float64),
  'status' : IDL.Text,
  'closeTime' : IDL.Opt(IDL.Int),
  'pair' : IDL.Text,
  'size' : IDL.Float64,
  'entryPrice' : IDL.Float64,
  'closeReason' : IDL.Opt(IDL.Text),
  'exitPrice' : IDL.Opt(IDL.Float64),
  'openTime' : IDL.Int,
});
export const BotState = IDL.Record({
  'rsi' : IDL.Float64,
  'lastPrice' : IDL.Float64,
  'consecutiveLosses' : IDL.Nat,
  'ema200' : IDL.Float64,
  'ema50' : IDL.Float64,
  'totalPnL' : IDL.Float64,
  'capital' : IDL.Float64,
  'isRunning' : IDL.Bool,
  'openTradesCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PnLSummary = IDL.Record({
  'totalTrades' : IDL.Nat,
  'totalPnL' : IDL.Float64,
  'winningTrades' : IDL.Nat,
  'winRate' : IDL.Float64,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCapital' : IDL.Func([IDL.Float64], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'closeTrade' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Text],
      [IDL.Int, IDL.Float64],
      [],
    ),
  'configure' : IDL.Func([BotConfig], [], []),
  'getAllTradeCountSorted' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  'getAllTradesSortedByTradeSize' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  'getBotState' : IDL.Func([], [BotState], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOpenTradesByTradeSize' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  'getOpenTradesCount' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  'getOpenTradesSorted' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  'getPnLSummary' : IDL.Func([], [PnLSummary], ['query']),
  'getTradeCount' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'manualTick' : IDL.Func([], [IDL.Text], []),
  'resetBot' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startBot' : IDL.Func([], [], []),
  'stopBot' : IDL.Func([], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BotConfig = IDL.Record({
    'pair' : IDL.Text,
    'maxTrades' : IDL.Nat,
    'apiKey' : IDL.Text,
    'apiSecret' : IDL.Text,
    'capital' : IDL.Float64,
  });
  const Trade = IDL.Record({
    'id' : IDL.Nat,
    'pnl' : IDL.Opt(IDL.Float64),
    'status' : IDL.Text,
    'closeTime' : IDL.Opt(IDL.Int),
    'pair' : IDL.Text,
    'size' : IDL.Float64,
    'entryPrice' : IDL.Float64,
    'closeReason' : IDL.Opt(IDL.Text),
    'exitPrice' : IDL.Opt(IDL.Float64),
    'openTime' : IDL.Int,
  });
  const BotState = IDL.Record({
    'rsi' : IDL.Float64,
    'lastPrice' : IDL.Float64,
    'consecutiveLosses' : IDL.Nat,
    'ema200' : IDL.Float64,
    'ema50' : IDL.Float64,
    'totalPnL' : IDL.Float64,
    'capital' : IDL.Float64,
    'isRunning' : IDL.Bool,
    'openTradesCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PnLSummary = IDL.Record({
    'totalTrades' : IDL.Nat,
    'totalPnL' : IDL.Float64,
    'winningTrades' : IDL.Nat,
    'winRate' : IDL.Float64,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCapital' : IDL.Func([IDL.Float64], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'closeTrade' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Text],
        [IDL.Int, IDL.Float64],
        [],
      ),
    'configure' : IDL.Func([BotConfig], [], []),
    'getAllTradeCountSorted' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
    'getAllTradesSortedByTradeSize' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
    'getBotState' : IDL.Func([], [BotState], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOpenTradesByTradeSize' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
    'getOpenTradesCount' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
    'getOpenTradesSorted' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
    'getPnLSummary' : IDL.Func([], [PnLSummary], ['query']),
    'getTradeCount' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'manualTick' : IDL.Func([], [IDL.Text], []),
    'resetBot' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startBot' : IDL.Func([], [], []),
    'stopBot' : IDL.Func([], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };